sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wh232629

  redis:
    host: localhost
    port: 6379
    #    password:
    database: 10

  wechat:
    appid: wxa0a57a3e8e614d17
    secret: aba470c667720fb8478eb0ebb6d5780a
